- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install mysql libraries
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: run and enable the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: connect to mysql server through root password
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.daws82s.online
    register: mysql_info

  # - name: Set root password
  #   ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
  #   when: mysql_info.failed is true 