- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: run and enable the service
    ansible.builtin.service:
      name: mysql-server
      state: started
      enabled: yes