- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: run and enable the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: connect to mysql server through root password
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.daws82s.online
   